# Generated by Django 2.2 on 2020-12-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20201222_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='timestmap',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='tweetlike',
            old_name='timestmap',
            new_name='timestamp',
        ),
    ]
